#!/usr/bin/env bash
# setup-ubuntu-rdp-guac.sh
# Installs and configures:
#  - XRDP + XFCE desktop
#  - Apache Guacamole (Docker-based)
#  - UFW firewall rules
#  - Optional GitHub repo sync
#
# Usage:
#   sudo ./setup-ubuntu-rdp-guac.sh --user myuser [--github-repo user/repo --create-github]
#
#   Optional env vars:
#     GITHUB_TOKEN, GIT_NAME, GIT_EMAIL

set -euo pipefail
IFS=$'\n\t'

###############################################
# Default config
###############################################
TARGET_USER=""
RDP_PORT=3389
GUAC_PORT=8080
INSTALL_FAIL2BAN=true
INSTALL_DIR="/opt/ubuntu-rdp-setup"
UBUNTU_DESKTOP="xfce4"
CREATE_GITHUB=false
GITHUB_REPO="${GITHUB_REPO:-}"
GITHUB_TOKEN="${GITHUB_TOKEN:-}"
GIT_NAME="${GIT_NAME:-}"
GIT_EMAIL="${GIT_EMAIL:-}"

###############################################
# Helper functions
###############################################
log()  { echo -e "\e[1;34m[INFO]\e[0m $*"; }
warn() { echo -e "\e[1;33m[WARN]\e[0m $*"; }
err()  { echo -e "\e[1;31m[ERROR]\e[0m $*" >&2; exit 1; }

###############################################
# Parse CLI args
###############################################
while [[ $# -gt 0 ]]; do
  case "$1" in
    --user) TARGET_USER="$2"; shift 2;;
    --rdp-port) RDP_PORT="$2"; shift 2;;
    --no-fail2ban) INSTALL_FAIL2BAN=false; shift;;
    --create-github) CREATE_GITHUB=true; shift;;
    --github-repo) GITHUB_REPO="$2"; CREATE_GITHUB=true; shift 2;;
    --git-name) GIT_NAME="$2"; shift 2;;
    --git-email) GIT_EMAIL="$2"; shift 2;;
    --install-dir) INSTALL_DIR="$2"; shift 2;;
    -h|--help) sed -n '1,120p' "$0"; exit 0;;
    *) warn "Unknown arg: $1"; shift;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  err "Please run this script as root (sudo)."
fi

###############################################
# Base system setup
###############################################
log "Updating system and installing XRDP + XFCE..."
apt-get update -y
apt-get install -y xrdp dbus-x11 ${UBUNTU_DESKTOP} ${UBUNTU_DESKTOP}-goodies xorgxrdp git curl ufw jq

if $INSTALL_FAIL2BAN; then
  apt-get install -y fail2ban
fi

###############################################
# Configure XRDP
###############################################
log "Configuring XRDP service..."
systemctl enable xrdp --now

cat > /etc/xrdp/startwm.sh <<'EOF'
#!/bin/sh
export XDG_SESSION_TYPE=x11
export DESKTOP_SESSION=xfce
startxfce4
EOF
chmod +x /etc/xrdp/startwm.sh

# Change default RDP port if needed
if [[ "$RDP_PORT" != "3389" ]]; then
  sed -i "s/^port=.*/port=${RDP_PORT}/" /etc/xrdp/xrdp.ini
  systemctl restart xrdp
fi

###############################################
# Add target user
###############################################
if [[ -n "$TARGET_USER" && ! $(id -u "$TARGET_USER" 2>/dev/null) ]]; then
  log "Creating user: $TARGET_USER"
  adduser "$TARGET_USER"
  usermod -aG sudo "$TARGET_USER"
fi

###############################################
# Firewall rules
###############################################
if command -v ufw >/dev/null 2>&1; then
  log "Configuring UFW..."
  ufw allow 22/tcp || true
  ufw allow ${RDP_PORT}/tcp || true
  ufw allow ${GUAC_PORT}/tcp || true
  ufw --force enable || true
fi

###############################################
# Fail2Ban setup
###############################################
if $INSTALL_FAIL2BAN; then
  log "Setting up Fail2Ban for XRDP..."
  cat > /etc/fail2ban/jail.d/xrdp.conf <<EOF
[xrdp]
enabled = true
port    = ${RDP_PORT}
filter  = xrdp
logpath = /var/log/auth.log
maxretry = 5
bantime = 600
EOF
  systemctl restart fail2ban || true
fi

###############################################
# Install Apache Guacamole via Docker Compose
###############################################
log "Installing Apache Guacamole (Docker stack)..."

GUAC_DIR="/opt/guacamole"
mkdir -p "$GUAC_DIR"
apt-get install -y docker.io docker-compose-plugin

cat > "$GUAC_DIR/docker-compose.yml" <<'EOF'
version: "3.8"
services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: always

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guac_db_user
      POSTGRES_PASSWORD: some_password
    depends_on:
      - guacd
      - postgres

  postgres:
    image: postgres:15
    container_name: guac-db
    restart: always
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guac_db_user
      POSTGRES_PASSWORD: some_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
EOF

cd "$GUAC_DIR"
docker compose up -d

sleep 10
if docker ps --format '{{.Names}}' | grep -q guacamole; then
  log "✅ Guacamole running: http://$(hostname -I | awk '{print $1}'):${GUAC_PORT}/guacamole"
  log "   Default login: guacadmin / guacadmin"
else
  warn "Guacamole container not detected; check logs with: docker compose logs"
fi

###############################################
# Save script artifacts locally
###############################################
mkdir -p "$INSTALL_DIR"
cp -f "$0" "$INSTALL_DIR/"
cat > "$INSTALL_DIR/README.md" <<EOF
# Ubuntu RDP + Guacamole Setup

Installed:
- XRDP + XFCE on port ${RDP_PORT}
- Guacamole (Docker) on port ${GUAC_PORT}
- Fail2Ban + UFW firewall
Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

Access:
- RDP:   <server-ip>:${RDP_PORT}
- Web:   http://<server-ip>:${GUAC_PORT}/guacamole
  (Default: guacadmin / guacadmin)
EOF

###############################################
# Optional GitHub commit/push
###############################################
cd "$INSTALL_DIR"
git init -q
[[ -n "$GIT_NAME" ]] && git config user.name "$GIT_NAME"
[[ -n "$GIT_EMAIL" ]] && git config user.email "$GIT_EMAIL"
git add -A
git commit -m "Initial Ubuntu RDP + Guacamole setup" || true

if $CREATE_GITHUB && [[ -n "$GITHUB_REPO" ]]; then
  if [[ -n "$GITHUB_TOKEN" ]]; then
    log "Creating GitHub repo ${GITHUB_REPO}..."
    GH_USER=$(cut -d'/' -f1 <<< "$GITHUB_REPO")
    GH_NAME=$(cut -d'/' -f2 <<< "$GITHUB_REPO")
    curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
         -d "{\"name\":\"${GH_NAME}\",\"private\":false}" \
         https://api.github.com/user/repos >/dev/null 2>&1 || true
    git remote add origin "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git"
    git branch -M main
    git push -u origin main --force
    git remote set-url origin "https://github.com/${GITHUB_REPO}.git"
  else
    warn "GITHUB_TOKEN not set, skipping GitHub push."
  fi
fi

###############################################
# Summary
###############################################
log "✅ Installation complete!"
cat <<EOF

==== SUMMARY ====
RDP access:     <server-ip>:${RDP_PORT}
Guacamole web:  http://<server-ip>:${GUAC_PORT}/guacamole
Login:          guacadmin / guacadmin
Install dir:    ${INSTALL_DIR}

Security Tips:
  - Change default Guacamole password immediately.
  - Restrict firewall ports or use a VPN.
  - For automatic startup: systemctl enable docker

EOF
